### ISSUE TITLE
libhid.dll not found.

### ISSUE THREAD

**Issue by nougator** [flok/pydualsense#11]
When I try to run my program I have this error `Exception has occurred: ImportError
Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll`
I have downloaded the binaries but where should I put them?

**Comment by flok** [comment]
I've put mine in the Windows\System32 folder. But you cant put them anywhere you want as long as you add the path to your environmental variables i think.

Thanks for the info. Will update the README with these instructions

**Comment by flok** [comment]
Updated the README with the infos. Thanks for this.

**Comment by nougator** [comment]
I putted it  in my path still doesn't work.

**Comment by flok** [comment]
You downloaded [hidapi](https://github.com/libusb/hidapi/releases/tag/hidapi-0.10.1) and put the hidapi.dll from the x64 folder in  C:\Windows\System32\ ?

Do you have 32 Bit Windows?

**Comment by nougator** [comment]
I have a 64 bits  computer with 64 bits windows. And I didn't putted it into the System32 in putted in the path, it's basically the same thing as putting in the System32.

**Comment by nougator** [comment]
And by the way it would better if don't have to put something in our path/System32 for those who want to create a game and then share it.

**Comment by flok** [comment]
> 
> 
> And by the way it would better if don't have to put something in our path/System32 for those who want to create a game and then share it.

That is entirely true. But i'm afraid i cant package the dll file with this package to prevent issues with licensing. If you put the dll in the folder of your running python script that you are working on it also works.

Is that a sufficient solution?

**Comment by nougator** [comment]
I did that too but I didn't worked

**Comment by flok** [comment]
do 
```python
import sys
print(sys.path)
```
inside your file and see if the folder your .py file is located is in you path and place the dll file in that folder. Checked just now that is works without a problem

**Comment by nougator** [comment]
I use python 3.9.

**Comment by nougator** [comment]
I'm wondering if the problem is that I'm using a venv

**Comment by flok** [comment]
venv is not an issue or problem.

Try to add:

```python

if sys.version_info >= (3,8):
    os.add_dll_directory(os.getcwd())

```

in the pydualsense.py before the ```import hid``` statement

**Comment by nougator** [comment]
The DLL should be here, right?
![Screenshot_2](https://user-images.githubusercontent.com/37145431/103444826-f8d7c000-4c6c-11eb-8b78-fe72ae4e3cbe.png)

**Comment by flok** [comment]
> 
> 
> The DLL should be here, right?
> ![Screenshot_2](https://user-images.githubusercontent.com/37145431/103444826-f8d7c000-4c6c-11eb-8b78-fe72ae4e3cbe.png)

Yes that looks good. Try the snipped from above and see if its working.

**Comment by nougator** [comment]
Thanks, it work!
