### ISSUE TITLE
The library seem to block the main thread.

### ISSUE THREAD

**Issue by nougator** [flok/pydualsense#12]

**Comment by flok** [comment]
It opens a Thread for receiving  / sending. 

Could you give a example where you encounter this ?

**Comment by nougator** [comment]
When I try to use it with pygame the window doesn't respond. it only happen when I'm using the lib, that's weird, I tried to fix (without success or I would have a pull request) and I saw that you're using threading.

**Comment by flok** [comment]
Will take a look at this in some days. Atm no idea why this wouldnt work as the report thread is create and should work in the background

**Comment by flok** [comment]
@nougator i think you forgot to update the screen with pygame.display.flip()

This simple example works fine
```python
import pygame
from pydualsense import *
pygame.init()

SCREEN = pygame.display.set_mode((300, 200))
ds = pydualsense()
ds.init()

RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

is_running = True
while is_running:
    if ds.state.circle:
        ds.light.setColorI(255,0,0)
        SCREEN.fill(GREEN)
    else:
        ds.light.setColorI(0,0,255)
        SCREEN.fill(BLUE)

    pygame.display.flip()
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

pygame.quit()
````

**Comment by nougator** [comment]
Oh thx
