### ISSUE TITLE
Mute button

### ISSUE THREAD

**Issue by Eudritch** [flok/pydualsense#20]
In fortnite mute button act as a **master mute** on the controller. I even went further and explore it on sound setting with and without headphones and it doesn't show incoming input when activated.

**Comment by flok** [comment]
If the mute button is lighted up it means the mic is muted by the controller itself. Maybe i'm misunderstanding the issue here. Please be more specific

**Comment by Eudritch** [comment]
When the mute button is lighted up the mic isn't muted by the controller. The controller stills hear everything.

**Comment by Eudritch** [comment]
Also is there a function where I can check if the mute button is being pressed.

**Comment by flok** [comment]
just pushed 0.5.2.5 which has a option to mute the microphone with the library. it also toggles the led accordingly.

therse is also a new variable micBtn in state which indicates if the button was pressed

**Comment by Eudritch** [comment]
As I'm reading your response I also made a new variable micBtn in the state which indicates if the button was pressed and also made the ability to mute and unmute the current using microphone. My only issue is that turning on the led takes a full second.

**Comment by Eudritch** [comment]
You take your time learning how to use a dualsense for Python. It helps to know people like you out there, and I appreciate it.
