### ISSUE TITLE
Is it possible to send input state on writeReport ?

### ISSUE THREAD

**Issue by sonizef** [flok/pydualsense#21]
Hi !

Is not an issue but I don't where I can ask my question :) 

1. Is it possible to get the current state of the controller and to send it to controller ?
It's not very clear, but I read my device with that 

`inReport = dualsense.device.read(dualsense.receive_buffer_size)`

And if I immediately send these data to my controller with that

`dualsense.device.write(inReport)`

It's not working properly.

2. Is it possible to send an input state ?
For exemple : What I need to write on my device if I want to simulate a click on my Square button ?
I think it's linked with my first question.

Thank you for your work!

**Comment by flok** [comment]
Sending input states to the controller is not supported. You can only send a feature report to it that changes settings like the triggers / lights.

**Comment by sonizef** [comment]
Is because pydualsense not supported this feature for now or is beacause hidapi not supported that?

My dualsense is detected like dualshock4 on my mac, and I think the dualshock 4 can receive input?

Thank you! :)

**Comment by flok** [comment]
The hidapi doesnt support to simulate input of the controller.

If you want the state of the controller its in the .state variable in the pydualsense class. See the examples folder for code
