### ISSUE TITLE
Arm/Raspberry Pi support

### ISSUE THREAD

**Issue by tahaj95** [flok/pydualsense#22]
Hi,

Sorry I'm not very processor/instruction literate and I'm impressed with what you've done. Any idea if I can get this to work on a raspberry pi 4b? Pip had no issues installing the module but just loading the module in an otherwise empty python script gives an error:

cffi.CDefError: cannot parse "ULONG_PTR Internal;
<cdef source string>:4:5: before: ULONG_PTR

This exception occurred after an earlier exception:

pycparser.plyparser.ParseError: <cdef source string>:4:5: before: ULONG_PTR

Sorry if this isn't relevant, but any pointers in the right direction would be greatly appreciated!

**Comment by flok** [comment]
The library used only works on windows and i dont really plan to make that possible.

**Comment by nougator** [comment]
Hmm, that would be cool though because we could make mini consoles and stuff like that using dualsense.

**Comment by parkerlreed** [comment]
This would be be great to have. hidapi is fully supported on Linux. There's nothing that should stop this from working.

**Comment by flok** [comment]
Thanks for the interest. I looked into it and i seems that the changed i made to the hidapi are not linux compatible. I will try to work out a way to make it also possible on linux with the current features.

**Comment by flok** [comment]
the new released version v0.5.5 supports the controller under linux with usb (tested on a ubuntu 20.04 vm).

Feedback is appreciated if you encounter any problems with the release

**Comment by parkerlreed** [comment]
@flok Thanks! I'll be able to test it a little later today.

**Comment by parkerlreed** [comment]
@flok Success! Working great on x86_64.
