### ISSUE TITLE
check this out

### ISSUE THREAD

**Issue by jonasfrey** [flok/pydualsense#23]
script attached, you willl need a few libraries to run it, mainly tkinter

**Comment by jonasfrey** [comment]
[controller_canvas.py.txt](https://github.com/flok/pydualsense/files/6053319/controller_canvas.py.txt)

**Comment by jonasfrey** [comment]
[controller_canvas.py.txt](https://github.com/flok/pydualsense/files/6055773/controller_canvas.py.txt)

**Comment by flok** [comment]
Please be more descriptive of what this is exactly, if its an example create a pull request with photos of it.
