### ISSUE TITLE
hidapi fails to install

### ISSUE THREAD

**Issue by Enigma3000** [flok/pydualsense#26]
Hi, trying to install pydualsense on my Nvidia Shield Pro 2019. I have termux installed. I get these errors when I try **pip install hidapi**:

hidapi/libusb/hid.c:47:10: fatal error: 'libusb.h' file not found
hidapi/linux/hid.c:44:10: fatal error: 'libudev.h' file not found

Any help is highly appreciated!

**Comment by Enigma3000** [comment]
ok, after copying hid.c to site-pacakges I now get a new error: **AttributeError: module 'hidapi' has no attribute 'Device'**

I need some help, please.

**~/hidapi-0.10.1 $ cp hid.c /data/data/com.termux/files/usr/lib/python3.9/site-packages/**
~/hidapi-0.10.1 $ python
Python 3.9.5 (default, May  5 2021, 12:32:19)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
**>>> from pydualsense import pydualsense, TriggerModes**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pydualsense/__init__.py", line 2, in <module>
    from .pydualsense import pydualsense, DSLight, DSState, DSTouchpad, DSTrigger, DSAudio
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pydualsense/pydualsense.py", line 10, in <module>
    class pydualsense:
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pydualsense/pydualsense.py", line 60, in pydualsense
    def __find_device(self) -> hidapi.Device:
**AttributeError: module 'hidapi' has no attribute 'Device'**

**Comment by Enigma3000** [comment]
BTW: My PS5 controller is paired and connected via Bluetooth on my Nvidia Shield Pro 2019 and fully working. I can navigate with it but still get this error. 

I haven't tried it with a cable though.

**Comment by Enigma3000** [comment]
Tried it wired now. Doesn't matter. Outputs the same error.

**Comment by flok** [comment]
Did you placed the dll of hidapi as described in the README in your workspace? This module is currently also only supported on Windows

**Comment by Enigma3000** [comment]
No, I figured a dll won't work on Android. Didn't know this wasn't supported. Too bad. Would love to control my PS5 with my Shield and in Kodi. Maybe you can add support. Would be cool!
