### ISSUE TITLE
Raspberry Pi library issue

### ISSUE THREAD

**Issue by d-i-ry** [flok/pydualsense#28]
Hi,

On the Raspberry Pi 4, I get the raised exception "OSError: Could not find any hidapi library"

I've read through the commit notes, and I see that Linux support's been expanded, but is there anything specific I need to do to make this work?

I've downloaded the hidapi v0.10.1 zip and extracted the x64 version of the hidapi.dll file to my python project folder. I then installed this lib with "pip install pydualsense"

But the pydualsense library can't find the DLL.

I've also tried dropping "hidapi.dll" into /home/pi/.local/lib/python3.7/site-packages/ since that's where hidapi.py is. No luck.

Thanks,
Ryan

**Comment by parkerlreed** [comment]
You need to install hidapi from your repo/python pip. 

```
sudo apt install python-hidapi
```

**Comment by flok** [comment]
I will add install instructions to the readme for linux based systems

**Comment by d-i-ry** [comment]
Thanks. That worked.

I'd really appreciate Linux setup steps because the new error is "OSError: Could not open connection to device." from hidapi.py line 256

I know the device can be reached because I'm able to run my own python script, reading the joystick and button-press values.

Thanks again,
Ryan

**Comment by parkerlreed** [comment]
hidapi is raw USB. You need elevated privileges to access it (or setup udev rule to set permissions)

**Comment by d-i-ry** [comment]
Oh. Well there's my problem. I'm connecting via Bluetooth!

I was hoping to use your library because I'm using a PS5 DualSense to control my robot wirelessly.

**Comment by flok** [comment]
> 
> 
> Oh. Well there's my problem. I'm connecting via Bluetooth!
> 
> I was hoping to use your library because I'm using a PS5 DualSense to control my robot wirelessly.

Yeah BT is not supported at the moment. Had a lot todo the last few month, still need to implement the crc32 check in python from DS4Windows so we can use the controller throught BT.

If you have time and are up for the challenge a PR with the CRC implementation would be highly appreciated. You can find the DS4Windows CRC32 implementation here: [crc32](https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Library/Crc32.cs). #9 is the issues for BT support.
