### ISSUE TITLE
Examples for Button/Joystick Control

### ISSUE THREAD

**Issue by chruzie** [flok/pydualsense#31]
Good Evening,

Just learning a bit of python I was wondering if you had any examples of controlling user input?

I tried reading the source code a bit and its just hanging if I set the states, im probably doing this wrong.

```
from pydualsense import *
# create dualsense
dualsense = pydualsense()

# find device and initialize
dualsense.init()

dualsense.state.ps = "True"
dualsense.sendReport()
time.sleep(2.5)
dualsense.state.ps = "False"
dualsense.sendReport()

# close device
dualsense.close()
```

help wanted

**Comment by flok** [comment]
Hey,

the library doesn't support on setting the state of the PS button for example, the only thing is changeable are the trigger setting and some colors. The only way to see a change in the buttons is by pressing the button on the controller and reading the variable.

Also the ```sendReport()``` function doesnt need to be called, the library start a background thread that constantly triggers the ```sendReport()``` function by itself.

If you want some examples look in the example folder in this repository. There you cant find some code snippets to read / write to the controller using the defined functions

**Comment by HenriDickel** [comment]
Is this a feature that could be added in the future? I would be very interested in controlling the buttons using python.

**Comment by flok** [comment]
No, because it would be only implemented that the code thinks the button is pressed, but you cant signal the Controller itself that its pressed.

**Comment by chruzie** [comment]
Thanks very much for your time
