### ISSUE TITLE
Bricks Controller!

### ISSUE THREAD

**Issue by FOGC123** [flok/pydualsense#58]
this bricked my controller because i forgot to use the ds.close() function

**Comment by parkerlreed** [comment]
What??

There's no way this could brick the controller.

There's a small reset pinhole on the back of the controller that should reset it if you happened to do anything weird.

**Comment by flok** [comment]
Also agree with this statement. This library is only using the Hid interface to communicate with the controller.

If you have any more substential logs or info feel free to open an issue with more than 1 sentence.

**Comment by FOGC123** [comment]
ok thanks i didnt know if it was actually this or just a coincidence.. the reset button did nothing ): expensive ass paperweight

**Comment by flok** [comment]
https://www.playstation.com/en-us/support/hardware/troubleshoot-dualsense

**Comment by FOGC123** [comment]
ive done that a billion times, thanks for tryna help tho
