### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by flok** [flok/pydualsense#9]
Currently this library only supports usb-c cable support. I want to add the  bluetooth support in the next weeks.

**Comment by nougator** [comment]
I'll try to work on that but I have to buy a bluetooth adapter.

**Comment by flok** [comment]
I also bought a Bluetooth 5.1 LE PCIE Adapter and will try it. So you dont need to if you dont want to.

This should be straight forward after we got the pairiing in Windows. The biggest rock should be finding out the ConnectionType of the controller at runtime.

**Comment by nougator** [comment]
That's not a problem, I would have bought a bluetooth adapter anyway but I struggle to find a bluetooth 5 adapter. Where did you got your?

**Comment by flok** [comment]
Gigabyte GC-WBAX200 got this one

**Comment by flok** [comment]
Started working on this. need to implement the hidp_getcaps function inside the hid library to get the outputreport length to determine the connection type of the dualsense controller

**Comment by Etaash-mathamsetty** [comment]
> Started working on this. need to implement the hidp_getcaps function inside the hid library to get the outputreport length to determine the connection type of the dualsense controller

I'll try making a PR for this (edit: seems like u already did it)
so it seems like you can detect bluetooth but you don't have the actual thing implemented
if you are still working on this, I will explain how it works
so you take 74 out of the 78 elements in the outReport array
you calculate a crc32 hash using a certain seed. (look at hid-playstation.c in the linux kernel)
then you bitshift the 4 bytes onto the last 4 elements of the array

**Comment by kit-nya** [comment]
I've added in the implementation for this, but it looks like there's still a few things that are probably missing. I think that the out reports probably need to have the flags correctly set whenever there's an update too, instead of just setting them true all the time, so I created functions for each of them, but haven't implemented them all yet.
